## Bitnami PostgreSQL image version
## ref: https://hub.docker.com/r/bitnami/postgresql/tags/
##
imageTag: 9.5.3-r6

## Specify a imagePullPolicy
## 'Always' if imageTag is 'latest', else set to 'IfNotPresent'
## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
##
# imagePullPolicy:
#

## PostgreSQL admin user
## ref: https://github.com/bitnami/bitnami-docker-postgresql#creating-a-database-user-on-first-run
##
postgresqlUsername: postgres

## PostgreSQL password
## ref: https://github.com/bitnami/bitnami-docker-postgresql#creating-a-database-user-on-first-run
##
# postgresqlPassword:

## Database to create
## ref: https://github.com/bitnami/bitnami-docker-postgresql#creating-a-database-on-first-run
##
# postgresqlDatabase:
