apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      securityContext:
        fsGroup: 1001
      containers:
      - name: {{ .Release.Name }}
        image: "jpbochi/local-dynamodb:{{ .Values.imageTag }}"
        imagePullPolicy: {{ default "" .Values.imagePullPolicy | quote }}
        resources:
          limits:
            cpu: {{ .Values.cpu }}
            memory: {{ .Values.memory }}
          requests:
            cpu: 100m
            memory: 100Mi
        args:
          - dynamodb
          - -dbPath
          - /data
          - -sharedDb
        ports:
        - name: dynamo
          containerPort: 8000
        volumeMounts:
        - name: dynamodb-data
          mountPath: /data
      volumes:
      - name: dynamodb-data
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}
{{- if and ($key := .Values.nodeSelector) ($value := .Values.nodeSelector) }}
      nodeSelector:
        {{- range $key, $value := .Values.nodeSelector }}
        {{ $key }}: {{ $value }}
        {{- end }}
{{- end }}
