apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  aws-access-key-id: {{ .Values.awsAccessKeyID | b64enc }}
  aws-secret-access-key: {{ .Values.awsSecretAccessKey | b64enc }}
