apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: {{ .Values.replicasCount }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
    spec:
      containers:
      - name: {{ .Release.Name }}
        image: "{{ .Values.image }}:{{ .Values.imageTag }}"
        imagePullPolicy: {{ default "" .Values.imagePullPolicy | quote }}
        resources:
          limits:
            cpu: {{ .Values.cpu }}
            memory: {{ .Values.memory }}
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: PG_USER
          value: {{ .Values.username }}
        - name: PG_PASS
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}
              key: postgresql-password
        - name: PG_ADDR
          value: {{ .Values.host }}
        - name: PG_PORT
          value: {{ .Values.hostPort | quote }}
        - name: PG_MAX_CLIENT_CONN
          value: {{ .Values.maxClientConnections | quote }}
        - name: PG_DEFAULT_POOL_SIZE
          value: {{ .Values.poolSize | quote }}
        - name: PG_SERVER_IDLE_TIMEOUT
          value: {{ .Values.serverIdleTimeout | quote }}
        ports:
        - name: pgbouncer
          containerPort: 6432
{{- if and ($key := .Values.nodeSelector) ($value := .Values.nodeSelector) }}
      nodeSelector:
        {{- range $key, $value := .Values.nodeSelector }}
        {{ $key }}: {{ $value }}
        {{- end }}
{{- end }}
