## Datadog docker-dd-agent image version
## ref: https://hub.docker.com/r/datadog/docker-dd-agent/
##
image: datadog/docker-dd-agent:11.3.585-dogstatsd-alpine

## Specify a imagePullPolicy
## 'Always' if imageTag is 'latest', else set to 'IfNotPresent'
## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
##
imagePullPolicy: Always

## Replicas Set count
replicasCount: 2

## Datadog API key
apiKey: ""

## Environment tag
envTags: ""

## Resource limits
cpu: 150m
memory: 200Mi

## Node selector
## comment it out if you do not need to use node selector
## e.g. "role: worker-general"
nodeSelector:
  role: worker-general
