apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: deis-monitor-influxdb
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: deis-monitor-influxdb
  template:
    metadata:
      labels:
        app: deis-monitor-influxdb
    spec:
      securityContext:
        fsGroup: 1001
      containers:
      - name: deis-monitor-influxdb
        image: quay.io/{{.Values.org}}/influxdb:{{.Values.docker_tag}}
        imagePullPolicy: {{.Values.pull_policy}}
{{- if or (.Values.limits_cpu) (.Values.limits_memory)}}
        resources:
          limits:
{{- if (.Values.limits_cpu) }}
            cpu: {{.Values.limits_cpu}}
{{- end}}
{{- if (.Values.limits_memory) }}
            memory: {{.Values.limits_memory}}
{{- end}}
{{- end}}
        env:
        - name: "USER"
          value: "root"
        ports:
        - containerPort: 8083
          name: admin
        - containerPort: 8086
          name: transport
          protocol: TCP
        - containerPort: 8084
          name: ssltransport
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /ping
            port: 8086
          initialDelaySeconds: 1
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /ping
            port: 8086
          initialDelaySeconds: 1
          timeoutSeconds: 1
        volumeMounts:
        - name: influxdb-data
          mountPath: /data
      volumes:
      - name: influxdb-data
        persistentVolumeClaim:
          claimName: deis-monitor-influxdb
