kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: deis-monitor-influxdb
  labels:
    app: deis-monitor-influxdb
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
    volume.beta.kubernetes.io/storage-class: standard
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storageSize }}
