## Docker image
##
image: "yukinying/chrome-headless:60.0.3096.2"

## Specify a imagePullPolicy
## 'Always' if imageTag is 'latest', else set to 'IfNotPresent'
## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
##
imagePullPolicy: Always

## Replicas Set count
replicasCount: 1

## Resource limits
cpu: 1000m
memory: 2G

## Node selector
## comment it out if you do not need to use node selector
## e.g. "role: worker-general"
nodeSelector:
  role: worker-spot
