name: s3-proxy
version: 0.1.3
description: Chart for S3 proxy
keywords:
- proxy
- s3
sources:
- https://github.com/pottava/aws-s3-proxy
maintainers:
- name: Clearbit
  email: ops+containers@clearbit.com
