## local-dynamodb image version
## ref: https://hub.docker.com/r/jpbochi/local-dynamodb/
##
imageTag: latest

## Specify a imagePullPolicy
## 'Always' if imageTag is 'latest', else set to 'IfNotPresent'
## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
##
imagePullPolicy: Always

## Resource limits
cpu: 300m
memory: 300Mi

## Node selector
##
## e.g. "role: worker-general"
nodeSelector:
  role: worker-general
