apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-cronjob
  labels:
    app: {{ .Release.Name }}-cronjob
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-cronjob
    spec:
      containers:
      - name: {{ .Release.Name }}-cronjob
        image: "{{ .Values.image }}"
        imagePullPolicy: {{ default "" .Values.imagePullPolicy | quote }}
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 50m
            memory: 50Mi
        command: ["/bin/bash", "-c", "/app/scheduler"]
        env:
        - name: NODE_ENV
          value: "{{ .Values.nodeEnv }}"
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}
              key: redis-url
        - name: PROXY_UPDATE_URL
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}
              key: proxy-url
        - name: PROXY_UPDATE_SCHEDULE
          value: "{{ .Values.schedule }}"
{{- if and ($key := .Values.nodeSelector) ($value := .Values.nodeSelector) }}
      nodeSelector:
        {{- range $key, $value := .Values.nodeSelector }}
        {{ $key }}: {{ $value }}
        {{- end }}
{{- end }}
