apiVersion: v1
kind: Service
metadata:
  name: deis-monitor-grafana
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    app: deis-monitor-grafana
    router.deis.io/routable: "true"
  annotations:
    #service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
    router.deis.io/domains: grafana1
    router.deis.io/connectTimeout: "10"
    router.deis.io/tcpTimeout: "1200"
spec:
  #type: LoadBalancer
  ports:
  - port: 80
    name: ui
    targetPort: ui
  selector:
    app: deis-monitor-grafana
